### ISSUE TITLE
Documentation: Configuration - service required "@contao.framework" as first argument

### ISSUE THREAD

**Issue by fatcrobat** [codefog/tags-bundle#10]
Hey there,

in the [configurations part of the documenation ](https://github.com/codefog/tags-bundle/blob/master/docs/02-config.md) the first argument for the services is missing. It requires "@contao.framework".

```
services:
    app.article_tags_manager:
        class: Codefog\TagsBundle\Manager\DefaultManager
        arguments:
            - "@contao.framework"
            - "tl_app_article"
            - "tags"
        tags:
            - { name: codefog_tags.manager, alias: app.article }
```

Otherwise it throws an error:

```
Type error: Argument 1 passed to Codefog\TagsBundle\Manager\DefaultManager::__construct() must implement interface Contao\CoreBundle\Framework\ContaoFrameworkInterface, string given
```
